### ISSUE TITLE
集群配置不稳定，3个服务端经常没有选举出leader，或者kill掉leader后新leader没选举出来，偶尔又可以，怎么查看问题？

### ISSUE THREAD

**Issue by attack-key** [Bwar/NebulaBeacon#1]
![image](https://user-images.githubusercontent.com/51818344/120261858-567b4180-c2cb-11eb-8361-feffe6906c29.png)

**Comment by Bwar** [comment]
昨天测试了，实际是选举成功的，有个状态信息没有更新对，导致不同节点显示不一致，这个周末我发个版本修复一下。

**Comment by Bwar** [comment]
已修复
